version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: domain.sample
    networks:
      - project_default
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:8.2.2-fpm-alpine3.17
    container_name: php
    networks:
      - project_default
    volumes:
      - ./src:/var/www/html/src
      - ./data:/var/www/html/data
      - ./vendor:/var/www/html/vendor

networks:
  project_default:
    external: true