version: '3.8'

services:
  nginx:
    build: 
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: domain.sample
    networks:
      - default
    ports:
      - 8888:80
      - 8889:443
    volumes:
      - ./src:/var/www/html/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    entrypoint: ./docker/php/entrypoint.sh
    container_name: mock-third-api-php
    networks:
      - default
    volumes:
      - .:/var/www/html
